language: perl

addons:
  postgresql: "9.1"

perl:
  - 5.10
  - 5.12
  - 5.14
  - 5.16

env:
  - TEST_SUITE=sanity
  - TEST_SUITE=docs
  - TEST_SUITE=webservices DB=mysql
  - TEST_SUITE=selenium DB=mysql
  - TEST_SUITE=webservices DB=pg
  #- TEST_SUITE=selenium DB=pg

matrix:
  exclude:
    - perl: 5.12
      env: TEST_SUITE=docs
    - perl: 5.14
      env: TEST_SUITE=docs
    - perl: 5.10
      env: TEST_SUITE=webservices DB=mysql
    - perl: 5.10
      env: TEST_SUITE=webservices DB=pg
    - perl: 5.10
      env: TEST_SUITE=selenium DB=mysql
    - perl: 5.10
      env: TEST_SUITE=selenium DB=pg
    - perl: 5.12
      env: TEST_SUITE=webservices DB=mysql
    - perl: 5.12
      env: TEST_SUITE=webservices DB=pg
    - perl: 5.12
      env: TEST_SUITE=selenium DB=mysql
    - perl: 5.12
      env: TEST_SUITE=selenium DB=pg
    - perl: 5.14
      env: TEST_SUITE=webservices DB=mysql
    - perl: 5.14
      env: TEST_SUITE=webservices DB=pg
    - perl: 5.14
      env: TEST_SUITE=selenium DB=mysql
    - perl: 5.14
      env: TEST_SUITE=selenium DB=pg

before_install:
  - git clone https://github.com/dklawren/qa.git -b master qa
  - sudo sysctl -w kernel.shmmax=268435456
  - sudo sysctl -w kernel.shmall=268435456

install: true

before_script:
  - mysql -u root mysql -e "GRANT ALL PRIVILEGES ON *.* TO bugs@localhost IDENTIFIED BY 'bugs'; FLUSH PRIVILEGES;"
  - psql -c "create user bugs CREATEDB;" -U postgres
  - psql -c "create database travis_ci_test;" -U postgres

script: ./qa/travis.sh

after_failure:
  - sudo cat /var/log/apache2/error.log

notifications:
  irc:
    channels:
      - "irc.mozilla.org#dkl"
    template:
      - "Bugzilla %{branch} : %{author} : %{message}"
      - "Commit Message : %{commit_message}"
      - "Commit Link : %{compare_url}"
      - "Build Link : %{build_url}"
  on_success: change
  on_failure: always
